spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectea
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080
logging:
  level:
    org.springframework: ERROR
jwt:
  signing:
    key: 59c7f3614ddc4bdc4809f4391782ac3b3893ab8feb6dedbe8ceb767763a37785
