spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectea
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
server:
  port: 8080